### ISSUE TITLE
Not working with npm install

### ISSUE THREAD

**Issue by kazzkiq** [beomy/svelte-hammer#2]
I'm getting error while trying to work with this lib and it seems the npm package **doesn't have any .js files at all**:

<img width="314" alt="Screen Shot 2020-02-17 at 17 54 53" src="https://user-images.githubusercontent.com/1953194/74685879-9b4e9800-51ae-11ea-95e6-c711e12e1fcc.png">

It just installs `package.json` and `README.md`.

**Comment by beomy** [comment]
Thank you for error reporting. I was missing bundle.js. So I added bundle.js. Check update version.

**Comment by kazzkiq** [comment]
Thanks for the fast reply.

A good practice to make sure your project isn't missing anything before release is to use [`prepublishOnly`](https://docs.npmjs.com/misc/scripts#description) script as a hook to run your build whenever you try to do a publish.

e.g. (`package.json`):

```json
{
  "name": "svelte-hammer",
  "version": "0.1.2",
  "description": "hammerjs for svelte",
  "main": "dist/bundle.js",
  "scripts": {
    "build": "webpack",
    "prepublishOnly": "npm run build"
  },
  ... the rest of the file goes here
```
