### ISSUE TITLE
Error with hammer library

### ISSUE THREAD

**Issue by nye** [beomy/svelte-hammer#5]
When I try to run my app with `rollup -c -w` I get the following error and can't compile:

```
SyntaxError: Unexpected token (6:12644) in ...../node_modules/svelte-hammer/dist/bundle.js
```

The thing is that if I try to use hammerjs alone (without `svelte-hammer`) I also get a similar error... any ideas on what's going on?

Thanks!

**Comment by beomy** [comment]
@nye, I'm sorry. I don't understand your question.

Are you used svelte-hammer like this?

```
<script>
  import { Hammer } from 'svelte-hammer'
  import { onMount } from 'svelte'

  onMount(() => {
    const hammer = new Hammer(document.querySelector('#test'))
    hammer.get('pan')
    hammer.on('pan', () => { console.log('t') })
  })
</script>

<h1 id="test">Hello!</h1>
```

Can I see simple code?

**Comment by nye** [comment]
It seems that I'm using `@rollup/plugin-replace` and it's causing some conflict with `svelte-hammer`. If I don't use `@rollup/plugin-replace` in my `rollup.config.js` everything works fine.

I'm going to try to fix and I'll tell you here if I succeed.

**Comment by nye** [comment]
Well, I don't know exactly why but in my `rollup.config.js` if I replace this code:

```
const production = !process.env.ROLLUP_WATCH;

...

replace({
	process: JSON.stringify({
		env: {
			isProd: production,
		}
	}),
}),
```

with this:

```
const production = !process.env.ROLLUP_WATCH;

...

replace({__isProd__: production}),
```

Everything works just fine now. 🤷🏻‍♂️
