### ISSUE TITLE
Svelte with typescript got error: Expected 2 arguments, but got 1.

### ISSUE THREAD

**Issue by KuanYu0729** [beomy/svelte-hammer#7]
Hi sir, 

I use svelte with typescript.

`<span use:tap on:tap={login}>login</span>`

But I get eslint error: `Expected 2 arguments, but got 1.`

I find out tap.d.ts RecognizerOptions must exist, but this argument of hammerjs is optional

Could you fixed it, please?

**Comment by beomy** [comment]
Thank you for error reporting. I updated new version(0.1.7) for optional hammer options
