### ISSUE TITLE
Build Error: window is not defined

### ISSUE THREAD

**Issue by eduardoliron** [beomy/svelte-hammer#9]
The component is returning an error on build, when I am using sveltekit --> ReferenceError: window is not defined

**Comment by eduardoliron** [comment]
I manage to solve the problem by loading `hammerjs` from the `onMount` lifecycle trigger:

`onMount(async () => { await import('hammerjs').then((Hammer) => { const hammer = new Hammer.default(slider) }))`

I've forgot to say that I'm runing sveltekit on vite

**Comment by beomy** [comment]
I think that using the window object in `hammerjs`.

So, it is thought that an error occurs when trying to access the window object at build time.

As you said, if you are using `sveltekit` then you need to use dynamic import in `onMount`.
